### PR TITLE
Setup Docker & Docker Compose

### PR DESCRIPTION
**Pull request by rocketstack-matt**
All server side cotainers are configured, UI still needs to be run manually for now.

Issue: #25

### CODE REVIEW

**Comment by DovOps** [comment]
Thanks @rocketstack-matt  - I'm still looking at this and whether we want to create a 'docker' branch for this to go in, off of main, rather than merge this into main. Let's discuss this some more with @mcleo-d  and @maoo  at the Members Meeting this week...

**Comment by maoo** [comment]
Nice work @rocketstack-matt !

My personal preference for my projects is to keep `Dockerfile` files and `docker-compose.yml` into the `main` branch; for k8s manifests (if and when needed) I normally create a separate repository, as it helps github visitors to get up and running as fast as possible.

My 2 cents of course; happy to discuss in person at FINOS Member Meeting.

**Comment by DovOps** [comment]
@rocketstack-matt  - I've got multiple failures on runs/builds in a few locations. We can try to troubleshoot together. So far, tried Azure linux  box (8core),  gitpod 8core, and my macbook pro with similar startup failures and/or a few waves of build failures.  I'd also like us to probably either use gradlew as defined, without installing gradle, or installing gradle and using the gradle cli from the path... To install gradle, but still use the ./gradlew wrapper makes little sense imo.

**Comment by rocketstack-matt** [comment]
Do you see what the errors are? I remember I had to switch to a ma CV one with 32GB as I started getting space failures. I can try and spin up a clean codespace later. 

Fair point on gradle, will take a look.

**Comment by rocketstack-matt** [comment]
I've updated the docker-compose to reference root mounted path to the code which seems to have fixed the compile issues you were seeing, not sure why I wasn't getting them previously, perhaps I was referencing cached images so I blatted all my container images locally and seems good now. I've also run this in two clean codespaces and started up first time. Worth noting I was able to run on an 8 core / 16GB but it did complain it was running out of CPU, no complaints on a 16 core / 64GB.

Gradle images have been cleaned up to remove unnecessary software installs.

**Comment by DovOps** [comment]
Tested on a macbook pro, and on a vanilla cloud VM (ubuntu 22.04) - both worked nicely. Thanks @rocketstack-matt !

**Pull request merged**
